name: Continuous Deployment

on:
  push:
    branches:
      - dev

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.PORT}}
          script: |
            cd ~/AffectCX-API
            git pull origin dev
            npm ci
            npm build
            pm2 restart AffectCX-API
