name: Continuous Integration

on:
  pull_request:
    branches:
      - dev

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build